version: '3.8'
services:
  web:
    build: .
    ports:
      - "2222:5000"
    environment:
      DATABASE_URL: postgresql://rps_user:rps_password@db:5432/rps_db
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rps_user
      POSTGRES_PASSWORD: rps_password
      POSTGRES_DB: rps_db
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data: