pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/RadwaSamirr/radwasamir.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-webpage:latest .'
            }
        }
    }
}

