pipeline {
    agent any

    environment {
        IMAGE_NAME = 'radwa-static-site'
        CONTAINER_NAME = 'radwa-static-container'
        PORT = '9094'
    }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    // Stop and remove the old container if it exists
                    sh '''
                    docker rm -f $CONTAINER_NAME || true
                    docker run -d -p $PORT:80 --name $CONTAINER_NAME $IMAGE_NAME
                    '''
                }
            }
        }
    }

    post {
        success {
            echo "✅ Website deployed at http://<your-server-ip>:$PORT"
        }
        failure {
            echo "❌ Build or deploy failed."
        }
    }
}
