pipeline {
    agent any

    environment {
        IMAGE_NAME = "radwasamir/static-web"
        CONTAINER_NAME = "my-static-web"
        PORT = "9094"
    }

    stages {
        stage('Checkout Code') {
            steps {
                // You already checked out in Declarative SCM, this is optional
                git branch: 'main', url: 'https://github.com/RadwaSamirr/radwasamir.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "🔧 Building Docker image..."
                    sh "docker build -t $IMAGE_NAME ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    echo "🚀 Running container..."
                    sh """
                        # Stop running container if exists
                        if [ \$(docker ps -q -f name=$CONTAINER_NAME) ]; then
                            docker stop $CONTAINER_NAME
                        fi
                        # Remove container if exists
                        if [ \$(docker ps -aq -f name=$CONTAINER_NAME) ]; then
                            docker rm $CONTAINER_NAME
                        fi
                        # Run the new container
                        docker run -d -p $PORT:80 --name $CONTAINER_NAME $IMAGE_NAME
                    """
                }
            }
        }
    }

    post {
        failure {
            echo '❌ Build or deploy failed.'
        }
        success {
            echo "✅ Website running at http://localhost:$PORT"
        }
    }
}
